### ISSUE TITLE
restart loop, bee doesn't connect

### ISSUE THREAD

**Issue by tamas6** [ethersphere/swarm-desktop#376]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x1ba8a0a]

goroutine 67 [running]:
github.com/ethersphere/bee/pkg/storer.New({0x26f2158, 0xc00015a190}, {0x0, 0x0}, 0xc0006310a0?)
	github.com/ethersphere/bee/pkg/storer/storer.go:554 +0x5ea
github.com/ethersphere/bee/pkg/node.bootstrapNode({0x26f2158, 0xc00015a190}, {_, _}, {{_, _, _}}, {0xc00023a840, 0x20, 0x21}, ...)
	github.com/ethersphere/bee/pkg/node/bootstrap.go:177 +0x15c9
github.com/ethersphere/bee/pkg/node.NewBee({0x26f2158, 0xc0000945a0}, {0x2168ee4, 0x5}, 0xc000b62060, {0x26f45c0?, 0xc000220008}, 0x1, {0x26fdf48, 0xc000094550}, ...)
	github.com/ethersphere/bee/pkg/node/node.go:599 +0x3517
github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNode({0x26f2158, 0xc0000945a0}, 0xc000094460, 0xc000285b80?, {0x26fdf48, 0xc000094550})
	github.com/ethersphere/bee/cmd/bee/cmd/start.go:295 +0x1505
github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync.func1()
	github.com/ethersphere/bee/cmd/bee/cmd/start.go:200 +0x3a
created by github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync
	github.com/ethersphere/bee/cmd/bee/cmd/start.go:199 +0x110
```

checked on darwin x64
attempts to fix: tried to fire up bee manually from command line, got the same result

**Comment by agazso** [comment]
Related issue with a workaround: https://github.com/ethersphere/bee/issues/4264

**Comment by tamas6** [comment]
> Related issue with a workaround: [ethersphere/bee#4264](https://github.com/ethersphere/bee/issues/4264)

This did the trick thanks 🙏 :

"Following the suggestion of @ldeffenb, I changed the use-postage-snapshot to false and the node started"


Issue is not resolved but has a solution ✅

**Comment by Cafe137** [comment]
Please reopen if the new release does not fix this issue.
