### ISSUE TITLE
Error in Redeem Code

### ISSUE THREAD

**Issue by tonytony32** [ethersphere/swarm-desktop#429]
When trying to reedeem one of the gift codes, the xBZZ were sent, but the xDAI remained in the gift wallet with the following error:

`Failed to fund: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32010,\"message\":\"InsufficientFunds, Balance is 99924330000000000 less than sending value \\u002B gas 99924658000000000\"},\"id\":52}", error={"code":-32010}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8726401847735940084773594008252ac9421d6d4c25b4cc8a347c1cd30dea2f4d2ece337ae880162da732efd040080c080a0eac36d36201bb0ce252fa0cfceacdbc4b2095f5ba5960936e6fe51778afc6303a03eb52d4b18a4540cab33611caaab7faf65866dbefe7fc89aba736507a4845dc8\"],\"id\":52,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://xdai.fairdatasociety.org", code=SERVER_ERROR, version=web/5.6.0)`

**Comment by tonytony32** [comment]
Detailed log: 

`GiftCardFund.tsx:75 Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32010,\"message\":\"InsufficientFunds, Balance is 99924329941923275 less than sending value \\u002B gas 99924657942175015\"},\"id\":52}", error={"code":-32010}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f872640184773599ff84773599ff8252ac9421d6d4c25b4cc8a347c1cd30dea2f4d2ece337ae880162da73299af7d380c001a0153872244292af98e68ba538a5273d1e5010f7d1a1708abb445c55bc38c59cf9a00e1853db11620a2266f3d7a5fb573b81c24369c7855fa7bb943c0f744c196d0a\"],\"id\":52,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://xdai.fairdatasociety.org", code=SERVER_ERROR, version=web/5.6.0)
    at e.value (index.js:219:1)
    at e.value (index.js:228:1)
    at index.js:253:32
    at d (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at i (index.js:5:58)
(anonymous) @ GiftCardFund.tsx:75
GiftCardFund.tsx:75 Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32010,\"message\":\"InsufficientFunds, Balance is 99924329941923275 less than sending value \\u002B gas 99924657942175015\"},\"id\":52}", error={"code":-32010}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f872640184773599ff84773599ff8252ac9421d6d4c25b4cc8a347c1cd30dea2f4d2ece337ae880162da73299af7d380c001a0153872244292af98e68ba538a5273d1e5010f7d1a1708abb445c55bc38c59cf9a00e1853db11620a2266f3d7a5fb573b81c24369c7855fa7bb943c0f744c196d0a\"],\"id\":52,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://xdai.fairdatasociety.org", code=SERVER_ERROR, version=web/5.6.0)
    at e.value (index.js:219:1)
    at e.value (index.js:228:1)
    at index.js:253:32
    at d (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at i (index.js:5:58)
(anonymous) @ GiftCardFund.tsx:75
content.js:1 Disconnected from polkadot{.js}-0x6e10e163a1550e8d-content`

**Comment by tonytony32** [comment]
Btw, MPB Intel running MacOs 14.6.1
